# kuri Theme Config @ version 1.0.0
# website: https://kuri.ink | cl@kuri.ink

# Yourself / 个人信息
nickname:  # 昵称
  - 南羽
motto:  # 一句话简介
  - Done is better than perfect.
logo:  # 头像
  - /images/fav.png
github:  # Github 个人主页地址
  - https://github.com/changyuu98

background: # 背景图片
  - https://api.ee123.net/img/bingimg/dayimg.jpg
iconfont: /css/iconfont.css

# SEO / 搜索引擎优化
fav: /images/fav.png # 浏览器标签页图标

# Sidebar / 侧边栏
sidebar:
  工具:
    百度翻译:
      - https://fanyi.baidu.com/mtpe-individual/transText#/
      - 百度翻译
    iLovePDF:
      - https://www.ilovepdf.com/
      - 文件转换
    ToolTT:
      - https://tooltt.com/#tooltt-code
      - 进制转换
    StackEdit:
      - https://stackedit.cn/#
      - Markdown
    See-Tool:
      - https://see-tool.com/timestamp-converter
      - 时间转换

  收藏夹:
    人人都是产品经理:
      - https://www.woshipm.com/
      - 产品社区
    菜鸟教程:
      - https://www.runoob.com/
      - 速查手册
    掘金:
      - https://juejin.cn/
      - 技术社区
    Stack Overflow:
      - https://stackoverflow.com/
      - 解决问题

sidebar_color:
  工具:
    - apps
    - mdui-text-color-blue
  收藏夹:
    - star
    - mdui-text-color-orange

# Header / 页眉信息
chizaobook: true # true / false 在页眉显示摛藻好句功能

# Social / 社交按钮
social:
  博客:
    - https://changyuu98.github.io/HexoBlog/
    - Blog
    - iconfont iconblog
  哔哩哔哩:
    - https://space.bilibili.com/446610057
    - B站
    - iconfont iconbili
  about me:
    - https://space.bilibili.com/446610057
    - 关于我
    - iconfont iconaboutme
  邮箱:
    - https://space.bilibili.com/446610057
    - 邮箱
    - iconfont iconemail 

# Music / 音乐播放器
aplayer:
  enable: true
  server: tencent
  type: playlist
  id: '9664169664'
  fixed: true
  volume: 0.7
  
# Footer / 页脚信息
## copyright / 版权
author:  # 作者名称
  - 申树杰
## remark / 备注
remark: ''
## Regist / 备案
regist: ''

# tools / 工具
analysis:
  platform: 51.la
  id:
  cd: